# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-18 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Owner',
            new_name='owner',
        ),
    ]
