# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-18 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20190718_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
